//! Emits one example of every generator response shape to
//! `contracts/generator-examples.json`; the TS test parses each with its Zod
//! schema. Compared by shape (keys and JSON types) because ids and times vary.

use std::sync::Arc;

use pos_core::config::BusinessType;
use pos_core::currency::CurrencyCode;
use pos_core::time::Timestamp;
use serde_json::{json, Value};
use uuid::Uuid;

use crate::builds::{BuildSettings, BuildSettingsView};
use crate::clients::{new_client_config, preview_receipt, NewClientInput};
use crate::github::RepoCheck;
use crate::store::{AssetKind, BuildStatus, BuildUpdate, IssuedLicenseRecord, Store};

fn png(width: u32, height: u32) -> Vec<u8> {
    let mut out = Vec::new();
    {
        let mut encoder = png::Encoder::new(&mut out, width, height);
        encoder.set_color(png::ColorType::Grayscale);
        encoder.set_depth(png::BitDepth::Eight);
        let mut writer = encoder.write_header().expect("header");
        writer
            .write_image_data(&vec![0; (width * height) as usize])
            .expect("data");
    }
    out
}

fn shape(v: &Value) -> Value {
    match v {
        Value::Object(map) => {
            Value::Object(map.iter().map(|(k, v)| (k.clone(), shape(v))).collect())
        }
        Value::Array(items) => Value::Array(items.first().map(shape).into_iter().collect()),
        Value::String(_) => json!("string"),
        Value::Number(_) => json!("number"),
        Value::Bool(_) => json!("bool"),
        Value::Null => json!("null"),
    }
}

#[test]
fn generator_response_shapes_match_the_contract_fixture() {
    let now: Timestamp = "2026-09-24T10:00:00.000Z".parse().expect("ts");
    let store = Arc::new(Store::open_in_memory().expect("store"));
    let config = new_client_config(&NewClientInput {
        display_name: "Acme Cafe".into(),
        client_slug: "acme-cafe".into(),
        business_type: BusinessType::Cafe,
        base_currency: CurrencyCode::KWD,
    });
    let id = store.create_client(&config, now).expect("client").client_id;
    let logo = png(200, 60);
    let detail = store
        .put_asset(id, AssetKind::ReceiptLogo, &logo, (200, 60), now)
        .expect("asset");
    store
        .record_license(
            &IssuedLicenseRecord {
                license_id: Uuid::now_v7(),
                client_id: id,
                device_name: "TILL-1".into(),
                fingerprint_hash: "ab".repeat(32),
                max_devices: 2,
                issued_at: now,
                expires_at: Some(now),
                token: "eyJ…".into(),
            },
            now,
        )
        .expect("license");
    let build = store
        .create_build(id, &"cd".repeat(32), "0.1.0", now)
        .expect("build");
    let build = store
        .update_build(
            build.build_id,
            &BuildUpdate {
                status: Some(BuildStatus::Succeeded),
                commit_sha: Some("c0ffee".into()),
                run_id: Some(1),
                run_url: Some("https://github.com/acme/pos/actions/runs/1".into()),
                artifact_id: Some(2),
                artifact_name: Some("pos-acme-cafe".into()),
                artifact_size: Some(3),
                download_path: Some("C:\\Users\\me\\Downloads\\x.zip".into()),
                message: Some("done".into()),
            },
            now,
        )
        .expect("update");

    let examples = json!({
        "client_detail": detail,
        "client_summary": store.list_clients().expect("list")[0],
        "issued_license": store.licenses(id).expect("licenses")[0],
        "build_record": build,
        "build_settings": BuildSettingsView { settings: BuildSettings::default(), token_configured: true },
        "repo_check": RepoCheck { default_branch: "main".into(), can_push: true, branch_found: true, workflow_found: false },
        "receipt_preview": preview_receipt(&detail.config, Some(&logo), now).expect("preview"),
    });

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../packages/shared/contracts/generator-examples.json"
    );
    let document = json!({
        "_comment": "Generated by apps/generator/src-tauri/src/contract_tests.rs (POS_REGENERATE_FIXTURES=1). Compared by shape.",
        "examples": examples,
    });
    if std::env::var_os("POS_REGENERATE_FIXTURES").is_some() {
        std::fs::write(
            path,
            serde_json::to_string_pretty(&document).expect("json") + "\n",
        )
        .expect("write");
    }
    let committed: Value =
        serde_json::from_str(&std::fs::read_to_string(path).expect("fixture")).expect("parse");
    assert_eq!(
        shape(&committed),
        shape(&document),
        "regenerate with POS_REGENERATE_FIXTURES=1"
    );
}
