//! Pins the JSON shape of `LicenseStatus` to
//! `contracts/license-status.examples.json`, which the TS test parses with
//! `LicenseStatusSchema`.

use pos_license::status::{HaltState, LicenseStatus, ValidLicense, ValidState};
use serde_json::{json, Value};
use uuid::Uuid;

const PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../packages/shared/contracts/license-status.examples.json"
);

#[test]
fn status_json_matches_contract() {
    let valid = LicenseStatus::Valid(ValidLicense {
        state: ValidState::Valid,
        license_id: Uuid::from_u128(0x0192_0000_0000_7000_8000_0000_0000_0001),
        client_id: Uuid::from_u128(0x8f14e45f_ceea_467a_9a4e_3b2f1c9d0a11),
        expires_at: Some("2027-01-01T00:00:00.000Z".parse().expect("ts")),
        last_seen_at: None,
        offline: true,
        grace_days_remaining: Some(5),
    });
    let mut examples = vec![serde_json::to_value(valid).expect("json")];
    for state in [
        HaltState::Missing,
        HaltState::InvalidToken,
        HaltState::FingerprintMismatch,
        HaltState::Expired,
        HaltState::Revoked,
        HaltState::GraceExhausted,
        HaltState::HardwareError,
        HaltState::StorageError,
    ] {
        examples.push(serde_json::to_value(LicenseStatus::halted(state, "reason")).expect("json"));
    }
    let document = json!({
        "_comment": "Generated by crates/pos-license/tests/status_contract.rs (POS_REGENERATE_FIXTURES=1).",
        "examples": examples,
    });
    if std::env::var_os("POS_REGENERATE_FIXTURES").is_some() {
        std::fs::write(
            PATH,
            serde_json::to_string_pretty(&document).expect("json") + "\n",
        )
        .expect("write");
    }
    let committed: Value =
        serde_json::from_str(&std::fs::read_to_string(PATH).expect("exists")).expect("parses");
    assert_eq!(committed, document);
}
