//! End-to-end token tests against the committed development key pair, plus
//! the cross-language fixture (`contracts/license-fixture.json`) that the
//! Supabase edge function's WebCrypto verifier is also tested against.

#![cfg(feature = "issuer")]

use pos_core::config::BusinessType;
use pos_core::time::Timestamp;
use pos_license::activation::ActivationRequest;
use pos_license::claims::{LicenseClaims, AUDIENCE, ISSUER};
use pos_license::issuer::{issue_license, IssueOptions, IssuerError, SigningKey};
use pos_license::keys::{key_id, parse_public_key_pem};
use pos_license::verify::{verify_license, Expected, Rejection};
use serde_json::{json, Value};
use uuid::Uuid;

const DEV_PRIVATE: &str = include_str!("../../../keys/dev/license-dev.private.pem");
const DEV_PUBLIC: &str = include_str!("../../../keys/dev/license-dev.public.pem");
const FIXTURE_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../packages/shared/contracts/license-fixture.json"
);

const CLIENT: Uuid = Uuid::from_u128(0x8f14e45f_ceea_467a_9a4e_3b2f1c9d0a11);

fn fp() -> String {
    "3f".repeat(32)
}

fn at(s: &str) -> Timestamp {
    s.parse().expect("timestamp")
}

fn key() -> SigningKey {
    SigningKey::from_unencrypted_pem(DEV_PRIVATE).expect("dev key")
}

fn expected(fingerprint: &str) -> Expected<'_> {
    Expected {
        client_id: CLIENT,
        fingerprint,
    }
}

fn fixture_claims() -> LicenseClaims {
    LicenseClaims {
        iss: ISSUER.into(),
        aud: AUDIENCE.into(),
        sub: CLIENT,
        jti: Uuid::from_u128(0x0192_0000_0000_7000_8000_0000_0000_0001),
        iat: 1_790_000_000, // 2026-09-21
        nbf: None,
        exp: Some(4_102_444_800), // 2100-01-01
        fp: fp(),
        client_slug: "dev-demo-cafe".into(),
        business_type: BusinessType::Cafe,
        max_devices: 3,
    }
}

#[test]
fn fixture_token_is_reproducible_and_verifies() {
    let key = key();
    let token = key.sign(&fixture_claims());
    let fixture = json!({
        "_comment": "Generated by crates/pos-license/tests/tokens.rs (POS_REGENERATE_FIXTURES=1). Signed with keys/dev.",
        "key_id": key.key_id(),
        "public_key_pem": key.public_key_pem(),
        "token": token,
        "claims": fixture_claims(),
    });
    if std::env::var_os("POS_REGENERATE_FIXTURES").is_some() {
        let pretty = serde_json::to_string_pretty(&fixture).expect("json") + "\n";
        std::fs::write(FIXTURE_PATH, pretty).expect("write fixture");
    }
    let committed: Value =
        serde_json::from_str(&std::fs::read_to_string(FIXTURE_PATH).expect("fixture exists"))
            .expect("fixture parses");
    assert_eq!(
        committed, fixture,
        "PKCS#1 v1.5 signatures are deterministic"
    );

    let public = parse_public_key_pem(DEV_PUBLIC).expect("public key");
    let verified = verify_license(
        &token,
        &public,
        &key_id(&public),
        &expected(&fp()),
        at("2026-09-23T00:00:00.000Z"),
    )
    .expect("fixture verifies");
    assert_eq!(verified.claims, fixture_claims());
}

fn issue(expires_at: Option<Timestamp>) -> String {
    let request = ActivationRequest {
        client_id: CLIENT,
        fingerprint: fp(),
        device_name: "TILL-01".into(),
        app_version: "0.1.0".into(),
    };
    let options = IssueOptions {
        client_slug: "dev-demo-cafe".into(),
        business_type: BusinessType::Cafe,
        max_devices: 2,
        expires_at,
    };
    issue_license(&key(), &request, &options, at("2026-09-23T00:00:00.000Z"))
        .expect("issues")
        .token
}

fn check(token: &str, fingerprint: &str, now: &str) -> Result<(), Rejection> {
    let public = parse_public_key_pem(DEV_PUBLIC).expect("public key");
    verify_license(
        token,
        &public,
        &key_id(&public),
        &expected(fingerprint),
        at(now),
    )
    .map(|_| ())
}

#[test]
fn issued_token_verifies_for_the_bound_machine_only() {
    let token = issue(None);
    assert_eq!(check(&token, &fp(), "2030-01-01T00:00:00.000Z"), Ok(()));
    assert_eq!(
        check(&token, &"00".repeat(32), "2030-01-01T00:00:00.000Z"),
        Err(Rejection::FingerprintMismatch)
    );
}

#[test]
fn expiry_is_enforced() {
    let token = issue(Some(at("2027-01-01T00:00:00.000Z")));
    assert_eq!(check(&token, &fp(), "2026-12-31T23:59:59.000Z"), Ok(()));
    assert!(matches!(
        check(&token, &fp(), "2027-01-01T00:00:00.000Z"),
        Err(Rejection::Expired(_))
    ));
}

#[test]
fn tokens_issued_in_the_future_are_rejected() {
    let token = issue(None);
    assert!(matches!(
        check(&token, &fp(), "2026-09-22T00:00:00.000Z"),
        Err(Rejection::NotYetValid(_))
    ));
}

#[test]
fn wrong_client_is_rejected() {
    let public = parse_public_key_pem(DEV_PUBLIC).expect("public key");
    let other = Expected {
        client_id: Uuid::from_u128(7),
        fingerprint: &fp(),
    };
    assert_eq!(
        verify_license(
            &issue(None),
            &public,
            &key_id(&public),
            &other,
            at("2026-10-01T00:00:00.000Z")
        ),
        Err(Rejection::WrongClient)
    );
}

#[test]
fn tampering_and_algorithm_games_fail() {
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use base64::Engine;

    let token = issue(None);
    let parts: Vec<&str> = token.split('.').collect();

    // Payload edited to raise max_devices.
    let mut claims: Value =
        serde_json::from_slice(&URL_SAFE_NO_PAD.decode(parts[1]).expect("b64")).expect("json");
    claims["max_devices"] = json!(999);
    let forged_payload = URL_SAFE_NO_PAD.encode(serde_json::to_vec(&claims).expect("json"));
    let forged = format!("{}.{}.{}", parts[0], forged_payload, parts[2]);
    assert!(matches!(
        check(&forged, &fp(), "2026-10-01T00:00:00.000Z"),
        Err(Rejection::InvalidToken(_))
    ));

    // alg: none with signature stripped.
    let none_header = URL_SAFE_NO_PAD.encode(br#"{"alg":"none","typ":"JWT"}"#);
    let none_token = format!("{none_header}.{}.", parts[1]);
    let err = check(&none_token, &fp(), "2026-10-01T00:00:00.000Z").expect_err("rejected");
    assert!(err.to_string().contains("RS256"), "{err}");

    // Signed by a different key.
    let stranger = SigningKey::generate(2048).expect("keygen");
    let foreign = stranger.sign(&fixture_claims());
    let err = check(&foreign, &fp(), "2026-10-01T00:00:00.000Z").expect_err("rejected");
    assert!(err.to_string().contains("different key"), "{err}");

    // Garbage.
    for junk in ["", "a.b", "a.b.c.d", "....", &"x".repeat(9000)] {
        assert!(check(junk, &fp(), "2026-10-01T00:00:00.000Z").is_err());
    }
}

#[test]
fn encrypted_key_round_trip() {
    let key = key();
    assert_eq!(
        key.to_encrypted_pem("short").map(|_| ()),
        Err(IssuerError::WeakPassphrase)
    );
    let pem = key
        .to_encrypted_pem("correct horse battery staple")
        .expect("encrypts");
    assert!(pem.starts_with("-----BEGIN ENCRYPTED PRIVATE KEY-----"));
    let unlocked =
        SigningKey::from_encrypted_pem(&pem, "correct horse battery staple").expect("unlocks");
    assert_eq!(unlocked.key_id(), key.key_id());
    assert_eq!(
        SigningKey::from_encrypted_pem(&pem, "wrong passphrase!!").map(|_| ()),
        Err(IssuerError::Unlock)
    );
}

#[test]
fn issuing_validates_options() {
    let request = ActivationRequest {
        client_id: CLIENT,
        fingerprint: fp(),
        device_name: "TILL-01".into(),
        app_version: "0.1.0".into(),
    };
    let now = at("2026-09-23T00:00:00.000Z");
    let mut options = IssueOptions {
        client_slug: "dev-demo-cafe".into(),
        business_type: BusinessType::Cafe,
        max_devices: 0,
        expires_at: None,
    };
    assert!(issue_license(&key(), &request, &options, now).is_err());
    options.max_devices = 1;
    options.expires_at = Some(at("2026-09-23T12:00:00.000Z"));
    assert!(issue_license(&key(), &request, &options, now).is_err());
}
