//! The fixed words printed on receipts, kitchen tickets and reports, in each
//! language the tills speak. Names, notes and shop texts are printed as the
//! shop typed them.

use pos_core::config::Locale;
use pos_core::sales::PaymentMethod;

pub struct Words {
    pub receipt: &'static str,
    pub date: &'static str,
    pub cashier: &'static str,
    pub customer: &'static str,
    pub tax_no: &'static str,
    pub refund_banner: &'static str,
    pub void_banner: &'static str,
    pub copy_banner: &'static str,
    pub discount: &'static str,
    pub subtotal: &'static str,
    pub tax: &'static str,
    pub total: &'static str,
    pub change: &'static str,
    pub cash: &'static str,
    pub card: &'static str,
    pub wallet: &'static str,
    pub loyalty: &'static str,
    pub voucher: &'static str,
    pub points_redeemed: &'static str,
    pub points_returned: &'static str,
    pub points_earned: &'static str,
    pub points_taken_back: &'static str,
    pub points_balance: &'static str,
    pub member: &'static str,
    pub member_until: &'static str,
    // Kitchen tickets.
    pub course: &'static str,
    pub guests: &'static str,
    pub void_ticket: &'static str,
    // Reports.
    pub x_report: &'static str,
    pub z_report: &'static str,
    pub till: &'static str,
    pub from: &'static str,
    pub to: &'static str,
    pub not_closed: &'static str,
    pub sales: &'static str,
    pub discounts: &'static str,
    pub refunds: &'static str,
    pub voids: &'static str,
    pub net_sales: &'static str,
    pub on: &'static str,
    pub no_payments: &'static str,
    pub payments_net: &'static str,
    pub cash_drawer: &'static str,
    pub opening_floats: &'static str,
    pub cash_sales: &'static str,
    pub cash_refunds: &'static str,
    pub expected: &'static str,
    pub counted: &'static str,
    pub variance: &'static str,
    pub shift_open: &'static str,
    pub shifts: &'static str,
    pub open: &'static str,
    pub first_receipt: &'static str,
    pub last_receipt: &'static str,
    pub grand_total: &'static str,
    pub printer_test: &'static str,
}

const EN: Words = Words {
    receipt: "Receipt",
    date: "Date",
    cashier: "Cashier",
    customer: "Customer",
    tax_no: "Tax No",
    refund_banner: "*** REFUND ***",
    void_banner: "*** VOID ***",
    copy_banner: "*** COPY ***",
    discount: "Discount",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "TOTAL",
    change: "Change",
    cash: "Cash",
    card: "Card",
    wallet: "Wallet",
    loyalty: "Loyalty points",
    voucher: "Voucher",
    points_redeemed: "Points redeemed",
    points_returned: "Points returned",
    points_earned: "Points earned",
    points_taken_back: "Points taken back",
    points_balance: "Points balance",
    member: "Member",
    member_until: "until",
    course: "COURSE",
    guests: "guests",
    void_ticket: "VOID",
    x_report: "X REPORT",
    z_report: "Z REPORT",
    till: "Till",
    from: "From",
    to: "To  ",
    not_closed: "Nothing closed (not a Z)",
    sales: "Sales",
    discounts: "Discounts",
    refunds: "Refunds",
    voids: "Voids",
    net_sales: "Net sales",
    on: "on",
    no_payments: "No payments",
    payments_net: "Payments (net)",
    cash_drawer: "Cash drawer",
    opening_floats: "Opening floats",
    cash_sales: "Cash sales",
    cash_refunds: "Cash refunds",
    expected: "Expected",
    counted: "Counted",
    variance: "Variance",
    shift_open: "A shift is still open: not counted yet.",
    shifts: "Shifts",
    open: "open",
    first_receipt: "First receipt",
    last_receipt: "Last receipt",
    grand_total: "Grand total",
    printer_test: "Printer test OK",
};

const AR: Words = Words {
    receipt: "فاتورة",
    date: "التاريخ",
    cashier: "الكاشير",
    customer: "الزبون",
    tax_no: "الرقم الضريبي",
    refund_banner: "*** مرتجع ***",
    void_banner: "*** ملغاة ***",
    copy_banner: "*** نسخة ***",
    discount: "خصم",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    total: "الإجمالي",
    change: "الباقي",
    cash: "نقداً",
    card: "بطاقة",
    wallet: "محفظة",
    loyalty: "نقاط الولاء",
    voucher: "قسيمة",
    points_redeemed: "نقاط مستخدمة",
    points_returned: "نقاط مستردة",
    points_earned: "نقاط مكتسبة",
    points_taken_back: "نقاط مسحوبة",
    points_balance: "رصيد النقاط",
    member: "عضوية",
    member_until: "حتى",
    course: "الطبق",
    guests: "ضيوف",
    void_ticket: "إلغاء",
    x_report: "تقرير X",
    z_report: "تقرير Z",
    till: "الجهاز",
    from: "من",
    to: "إلى",
    not_closed: "لم يُغلق شيء (ليس تقرير Z)",
    sales: "المبيعات",
    discounts: "الخصومات",
    refunds: "المرتجعات",
    voids: "الملغاة",
    net_sales: "صافي المبيعات",
    on: "على",
    no_payments: "لا توجد مدفوعات",
    payments_net: "المدفوعات (صافي)",
    cash_drawer: "درج النقود",
    opening_floats: "رصيد الافتتاح",
    cash_sales: "مبيعات نقدية",
    cash_refunds: "مرتجعات نقدية",
    expected: "المتوقع",
    counted: "المعدود",
    variance: "الفرق",
    shift_open: "وردية ما زالت مفتوحة: لم يُعدّ الدرج بعد.",
    shifts: "الورديات",
    open: "مفتوحة",
    first_receipt: "أول فاتورة",
    last_receipt: "آخر فاتورة",
    grand_total: "الإجمالي العام",
    printer_test: "تمت تجربة الطابعة بنجاح",
};

pub fn words(language: Locale) -> &'static Words {
    match language {
        Locale::En => &EN,
        Locale::Ar => &AR,
    }
}

pub fn is_rtl(language: Locale) -> bool {
    language == Locale::Ar
}

impl Words {
    pub fn method(&self, method: PaymentMethod) -> &'static str {
        match method {
            PaymentMethod::Cash => self.cash,
            PaymentMethod::Card => self.card,
            PaymentMethod::Wallet => self.wallet,
            PaymentMethod::Loyalty => self.loyalty,
            PaymentMethod::Voucher => self.voucher,
        }
    }
}
